name: Automate Data Preprocessing

# Trigger: Jalan setiap kali ada push ke branch main
on:
  push:
    branches:
      - main
    paths:
      - 'preprocessing/automate_Nalendra.py' # Hanya jalan jika script berubah
      - 'namadataset_raw/**'                 # Atau jika data mentah berubah

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Izin Wajib agar Action bisa nge-push balik ke repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run Preprocessing Script
        run: |
          # Masuk ke folder preprocessing dan jalankan script
          cd preprocessing
          python automate_Nalendra.py

      - name: Commit and Push Processed Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Cek apakah ada perubahan pada file csv output
          git add preprocessing/namadataset_preprocessing/*.csv
          
          # Commit jika ada perubahan, jika tidak skip agar tidak error
          git commit -m "Auto-update processed dataset" || echo "No changes to commit"
          git push